### ISSUE TITLE
RainFARM stochastic precipitation downscaling

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#23]
This is a tracking issue for the final integration of *RainFARM stochastic precipitation downscaling metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/rainfarm)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_rainfarm.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@jhardenberg 
@earnone

**Comment by JaroCamphuijsen** [comment]
@bouweandela Running this metric on DAS5 (with `/var/scratch2/bandela/c3s-cmip5/output1` as my CMIP5 rootpath in the config-user.yml file) gives a permission error:

`
PermissionError: [Errno 13] Permission denied: b'/var/scratch2/bandela/c3s-cmip5/output1/ICHEC/EC-EARTH/historical/day/atmos/day/r1i1p1/pr/latest/pr_day_EC-EARTH_historical_r1i1p1_19900101-19991231.nc'
`

**Comment by jhardenberg** [comment]
Problems with the "calculate" interface of this recipe:

1) The description (on the RHS) of the option "target grid" is wrong. Please write "Regrid input data to this resolution. In degrees. Can also be the name of one of the input datasets"
2) The most important parameter of RainFARM, `nf` , is missing ! You can describe it as "number of subdivisions for downscaling" 
3) Set "slope" to 0 by default (this way the slope will be automatically computed from the large scales)
4) The "Weights Climo" option should be either "False" or the name of an input netcdf file pointing to a high resolution climatology. Examples of such files are available here (collected for another project): http://wilma.to.isac.cnr.it/diss/medscope/rainfarm/
   If it is impossible to implement this functionality then it is better to hide this option.

**Comment by jhardenberg** [comment]
- Also option `nens` (the number of stochastic downscaling ensemble members to generate) cannot be selected.
- If I select multiple models, only the first model is included in the recipe.

**Comment by earnone** [comment]
The online calculation works fine on a some examples I tried.

A few further comments:

1.  I find the `target grid` option confusing: since the user will want to downscale the original dataset to a new resolution, it may read this `target grid` as the final one. I guess this is instead controlled by `nf` as mentioned by @jhardenberg. I would therefore remove the `target_grid` and leave only the `nf`option. 

2. @jhardenberg options `conserve global `and `conserve smooth` could probably be hidden as they can confuse the reader and add possible problems?

3. the geographical box to be considered cannot be changes.

**Comment by jhardenberg** [comment]
Issues in the landing page of this metric:

- In the "metric results interactive plot"
   - Do not plot the png images (they are overlaid on a world map, which does not make sense)
   - We will prepare and send you two new example nc files to plot

**Comment by jhardenberg** [comment]
RainFARM is missing a "calculate" logo in the Metrics & Diagnostics page https://portal.c3s-magic.eu/#/diagnostics and a "calculate" button in the corresponding landing page (checked on portal.c3s-magic.eu)

**Comment by jhardenberg** [comment]
In the settings please change
"n Ensemble" --> "Ensemble"
"n Subdivisions" --> "Subdivisions"

**Comment by jhardenberg** [comment]
Currently not running, the message is 
```
Results for process rainfarm:
4) JSONObject["statuslocation"] not found.
```

**Comment by rvanharen** [comment]
> Currently not running, the message is
> 
> ```
> Results for process rainfarm:
> 4) JSONObject["statuslocation"] not found.
> ```

@jhardenberg Thanks, we're looking into it.

**Comment by jhardenberg** [comment]
The "weights_climo" option has been deactivated for the demo, but it should be included in the end.
Currently it works by either leaving it set to "FALSE" (default) or using it (yes, sorry, the variable changes type - not nice) to specify a filename of a reference climatology. I could provide at least two such reference climatologies to be used, but the problem is that we would then need to store them somewhere in order to use them. As an alternative, maybe the user could upload his/her own file ? How do we proceed to implement this?

**Comment by jhardenberg** [comment]
There should be an option NOT to regrid the input dataset (removing regridding from the preprocessor in the recipe)

**Comment by bouweandela** [comment]
> we would then need to store them somewhere in order to use them.

They should be stored in the directory defined under `auxiliary_data_dir` in the config-user.yml file and the recipe should use a relative path to that directory.
