### ISSUE TITLE
Blocking metrics and indices

### ISSUE THREAD

**Issue by yifatdzigan** [c3s-magic/c3s-magic-metric-status#5]
This is a tracking issue for the final integration of *Blocking metrics and indices metric* into the MAGIC framework.

This is also a place for discussion and updates on the current status, problems and questions related to this metric.

**Links:**
----------

[Portal](https://portal.c3s-magic.eu/#/diagnostics/blocking)
[Recipe](https://github.com/ESMValGroup/ESMValTool/blob/version2_development/esmvaltool/recipes/recipe_miles_block.yml)
For an overview of the current status of all metrics see [MAGIC Metrics Final Integration Checklist](https://docs.google.com/spreadsheets/d/1LFhEuL6w9KBqFmujVXXN6qj98jigMIPArYkSVKB_Frw/edit#gid=0)

**Contacts:**
--------------
@jhardenberg 
@earnone

**Comment by yifatdzigan** [comment]
@bpmweel Recipe works. Ready for WPS integration

**Comment by bpmweel** [comment]
@jhardenberg Could you please take a look at the blocking metric in the portal-dev wps page to check whether you have any feedback. If not we will consider it completed for the wps.

**Comment by jhardenberg** [comment]
Cool @bpmweel , thanks for the significant improvements!
Well, I see two residual issues:
1) There are now many models and experimenst to choose from. In selecting "ensemble" (the rip number) I am allowed to choose among a huge list of possible rip numbers. The problem is that not all combinations of model/experiment/rip exist in the CDS (or exist at all). 
So for example selecting model=GFDL_ESM2G, experiment=rcp85 and ensemble=r1i1p128 I obviously end up with an error in the calculation. Would it be possible to filter the rip numbers once model and experiment have been selected so that only meaningful combinations can be chosen? 
2) There are actually several other possible "reference_datasets" in the DKRZ pool on Jasmin, in addition to ERA-Interim. Would it make sense to add a few more to choose from?

**Comment by bpmweel** [comment]
@jhardenberg 

1. This is a known issue and limitation of WPS that we are not able to solve generally. Solving it in the portal is likely more effort than we can afford in the scope of the project.
2. I think it would make sense to add at least one more reference dataset, do you have any preference? We are limited in harddisk space on our WPS machine, so we cannot add all dkrz data.

**Comment by earnone** [comment]
The current limitation of models and especially ensemble member is much better. However, the blocking metrics calculation fails with default settings given in the portal, while they seem reasonable and should work.

**Comment by jhardenberg** [comment]
Suddenly this diagnostic does not have any more settings in the wps!

**Comment by jhardenberg** [comment]
Issues for the landing page of this metric:
1) In "Settings" , "Variable" says "geopotential height" but it should also specify that it is at 500hPa 
2) In "Settings" it says "Ensamble" --> that should be "Ensemble"
3) In the "Metric Results" interactive maps, the selection of "Tibaldi and Molteni 1990" does not work (it dows not work since it is actually a timeseries and here it is plotted as a map)

**Comment by bpmweel** [comment]
@jhardenberg We have fixed all the issues that we are able to fix at this time.

A known issue is that you cannot select different reference models this can only be fixed when we deploy the wps on lot1, where more data is available.

**Comment by jhardenberg** [comment]
After getting feedback from a coauthor, we updated the description of the diagnostic in the landing page (diagnostics & metrics). I prepared directly aPR, which you just need to accept:
https://github.com/c3s-magic/c3s-magic-frontend/pull/253

**Comment by yifatdzigan** [comment]
> Issues for the landing page of this metric:

> 3. In the "Metric Results" interactive maps, the selection of "Tibaldi and Molteni 1990" does not work (it dows not work since it is actually a timeseries and here it is plotted as a map)

Unfortunately we can not remove only one of the layers, so we will have to keep it as it is.

**Comment by nielsdrost** [comment]
Moved all outstanding issues to the wps(https://github.com/c3s-magic/c3s-magic-wps) and frontend(https://github.com/c3s-magic/c3s-magic-wps) repo issues. Please report additional issues there.
